theme: "hugo-PaperMod"
baseURL: https://dgemoets.github.io/
languageCode: en-us
title: My New Hugo Site
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/

markup:
  goldmark:
    renderer:
      unsafe: true
